#!/usr/bin/env python3
"""Regenerate docs/INDEX.md from the YAML frontmatter of every doc.

Usage:
    python3 tools/reindex.py           # rewrite docs/INDEX.md
    python3 tools/reindex.py --check   # exit 1 if the index is stale (CI)

Deliberately dependency-free: parses only the flat subset of YAML we use.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
INDEX = DOCS / "INDEX.md"

SECTIONS = [
    ("design", "Design", "What the game is."),
    ("tech", "Technical", "How it gets built."),
    ("process", "Process", "How we work, what we decided, what we must not do."),
    ("art", "Art & Audio", "Visual and audio direction."),
]

STATUS_MARK = {
    "draft": "✎ draft",
    "proposed": "◆ proposed",
    "accepted": "✔ accepted",
    "superseded": "✗ superseded",
}


def parse_frontmatter(path: Path) -> dict[str, object] | None:
    """Return the frontmatter mapping, or None if the file has none."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    _, _, rest = text.partition("---\n")
    block, sep, _ = rest.partition("\n---")
    if not sep:
        return None

    meta: dict[str, object] = {}
    for line in block.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, _, raw = line.partition(":")
        if not _:
            continue
        key, raw = key.strip(), raw.strip()
        if raw.startswith("[") and raw.endswith("]"):
            inner = raw[1:-1].strip()
            meta[key] = [v.strip() for v in inner.split(",") if v.strip()] if inner else []
        else:
            meta[key] = raw.strip("\"'")
    return meta


def collect() -> list[tuple[str, dict[str, object], Path]]:
    docs = []
    for folder, _, _ in SECTIONS:
        for path in sorted((DOCS / folder).glob("*.md")):
            meta = parse_frontmatter(path)
            if meta and meta.get("id"):
                docs.append((folder, meta, path))
    return docs


def render(docs) -> str:
    out: list[str] = [
        "<!-- GENERATED BY tools/reindex.py — DO NOT EDIT BY HAND -->",
        "",
        "# Project SHE — Documentation Index",
        "",
        f"_Regenerated {date.today().isoformat()} · {len(docs)} documents_",
        "",
        "Start with [DES-001 Vision & Pillars](design/DES-001-vision-and-pillars.md), "
        "then [DES-002 Core Loop](design/DES-002-core-loop.md).",
        "Live unresolved decisions: [OPEN-QUESTIONS.md](OPEN-QUESTIONS.md).",
        "",
    ]

    for folder, heading, blurb in SECTIONS:
        rows = [(m, p) for f, m, p in docs if f == folder]
        out += [f"## {heading}", "", f"_{blurb}_", ""]
        if not rows:
            out += ["_None yet._", ""]
            continue
        out += ["| ID | Document | Status | Updated | Related |", "|---|---|---|---|---|"]
        for meta, path in rows:
            rel = path.relative_to(DOCS).as_posix()
            status = STATUS_MARK.get(str(meta.get("status", "")), str(meta.get("status", "—")))
            related = ", ".join(meta.get("related") or []) or "—"
            out.append(
                f"| `{meta['id']}` | [{meta.get('title', path.stem)}]({rel}) "
                f"| {status} | {meta.get('updated', '—')} | {related} |"
            )
        out.append("")

    # Tag cloud — every tag mapped to the docs carrying it.
    tags: dict[str, list[str]] = {}
    for _, meta, _ in docs:
        for tag in meta.get("tags") or []:
            tags.setdefault(str(tag), []).append(str(meta["id"]))
    out += ["## By Tag", ""]
    for tag in sorted(tags):
        out.append(f"- **{tag}** — {', '.join(sorted(tags[tag]))}")
    out.append("")

    return "\n".join(out)


def main() -> int:
    docs = collect()
    if not docs:
        print("no docs with frontmatter found", file=sys.stderr)
        return 1

    content = render(docs)
    check = "--check" in sys.argv

    if check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        # Ignore the regeneration date line when comparing.
        strip = lambda s: "\n".join(l for l in s.splitlines() if not l.startswith("_Regenerated"))
        if strip(current) != strip(content):
            print("docs/INDEX.md is stale — run: python3 tools/reindex.py", file=sys.stderr)
            return 1
        print("index up to date")
        return 0

    INDEX.write_text(content, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT)} ({len(docs)} docs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
